name: CI/CD Pipeline

on:
  workflow_dispatch: # Ermöglicht das manuelle Starten
  push:
    branches:
      # - main
      - develop
  pull_request:
    branches:
      # - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: pytest tests/

  deploy_dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Development
        run: echo "Deploying to Development Environment"

  deploy_staging:
    runs-on: ubuntu-latest
    needs: deploy_dev
    environment:
      name: staging
      url: https://staging.example.com
    steps:
      - name: Approval for Staging
        run: echo "Approval required for Staging"

  deploy_prod:
    runs-on: ubuntu-latest
    needs: deploy_staging
    environment:
      name: production
      url: https://prod.example.com
    steps:
      - name: Approval for Production
        run: echo "Approval required for Production"
